### ISSUE TITLE
"Waiting to reconnect.."

### ISSUE THREAD

**Issue by lawabider** [MicrosoftDocs/windows-driver-docs#503] opened 2018-05-16 15:27 UTC
I can't get it to connect...sigh. I've tried restarting the target, opening firewalls...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67e01ae1-4090-c201-aed8-3d416344db7f
* Version Independent ID: b0a983c8-1386-1ba9-7d62-ac3a8a09b0cf
* Content: [Supported Ethernet NICs for Network Kernel Debugging in Windows 10](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/supported-ethernet-nics-for-network-kernel-debugging-in-windows-10#span-idvendorid8086intelcorporationspanspan-idvendorid8086intelcorporationspanspan-idvendorid8086intelcorporationspanvendor-id-8086-intel-corporation)
* Content Source: [windows-driver-docs-pr/debugger/supported-ethernet-nics-for-network-kernel-debugging-in-windows-10.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/supported-ethernet-nics-for-network-kernel-debugging-in-windows-10.md)
* Service: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment] 2018-05-16 16:43
Duplicate of Issue 504

**Closed by EliotSeattle** 2018-05-16 16:43 UTC
