### ISSUE TITLE
New bugcheck code

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#3195] opened 2022-07-09 22:16 UTC
I've analyzed a Windows memory dump file by using WinDBG which returned the below information

Unknown bugcheck code (1aa)
Unknown bugcheck description
Arguments:
Arg1: 00000039d76edad0
Arg2: 0000000000000003
Arg3: ffffd680fd09e900
Arg4: fffffc03cd5b1598

I could not find any information about this bugcheck code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b673ca8-6772-5979-ab72-520272ec75f6
* Version Independent ID: 94a3eab1-0f45-fbdc-c7f1-54418d82a8c7
* Content: [Kernel Live Dump Code Reference - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-code-reference-live-dump)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-code-reference-live-dump.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-code-reference-live-dump.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by tedhudek** [comment] 2022-07-11 17:43
Looks to be duplicate of #3194

**Closed by tedhudek** 2022-07-11 17:43 UTC
Labels: Pri2, windows-hardware/prod, debugger/tech
