### ISSUE TITLE
does not seem to work for serial ports in Windows 10

### ISSUE THREAD

**Issue by cinderbdt** [MicrosoftDocs/windows-driver-docs#2105] opened 2020-03-21 02:38 UTC
This doesn't seem to work for serial ports in Windows 10?
`rundll32.exe devmgr.dll,DeviceProperties_RunDLL /MachineID "" /DeviceID "ACPI\VEN_PNP&DEV_0501"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496b0399-54a7-d7df-2905-f727e32ea3c1
* Version Independent ID: d8d259f2-27f7-2b08-83ff-5750ed0db982
* Content: [Invoking a Device Properties Dialog Box from Command-line Prompt - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/invoking-a-device-properties-dialog-box-from-a-command-line-prompt)
* Content Source: [windows-driver-docs-pr/install/invoking-a-device-properties-dialog-box-from-a-command-line-prompt.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/invoking-a-device-properties-dialog-box-from-a-command-line-prompt.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment] 2020-07-22 21:28
Duplicate of #2104

**Closed by tedhudek** 2020-07-22 21:28 UTC
Labels: Pri2, doc-bug, product-feedback, windows-devices/tech, windows-hardware/prod
