### ISSUE TITLE
EhStorCertMgr

### ISSUE THREAD

**Issue by riback** [MicrosoftDocs/windows-driver-docs#1692] opened 2019-07-29 15:39 UTC
I installed WDK, SDK, ADK, visualstudio on Windows 10 1809 and 1903 and could not find any files named EhStorCertMgr*.*. 
I then downloaded the appliance and mounted it - still no sign of EhStorCertMgr*.* files anywhere.
Can you please just make these files available for download, perhaps even on GitHub in this project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9205186b-f671-0ac6-d0a3-2c630d9a1525
* Version Independent ID: def78a86-e830-cb69-f15c-0d939bb78e13
* Content: [Enhanced Storage Certificate Management Tool - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/enhanced-storage-certificate-management-tool)
* Content Source: [windows-driver-docs-pr/devtest/enhanced-storage-certificate-management-tool.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/enhanced-storage-certificate-management-tool.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment] 2019-08-14 00:24
Duplicate of Issue #1691

**Closed by EliotSeattle** 2019-08-14 00:24 UTC
Labels: Pri2, duplicate, windows-devices/tech, windows-hardware/prod
