### ISSUE TITLE
The information in this page is outdated. Please update the information.

### ISSUE THREAD

**Issue by SrinivasanChinnadurai** [MicrosoftDocs/windows-driver-docs#2856] opened 2021-07-20 10:19 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f16fae-1b9d-6f21-dbd5-e5fa22118685
* Version Independent ID: 4e09a919-7b21-31a8-7369-78b40cea209d
* Content: [Buy hardware for using MITT - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/spb/multi-interface-test-tool--mitt--#feedback)
* Content Source: [windows-driver-docs-pr/spb/multi-interface-test-tool--mitt--.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/spb/multi-interface-test-tool--mitt--.md)
* Product: **windows-hardware**
* Technology: **spb**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment] 2021-07-20 18:42
Dupe of #2857

**Closed by tedhudek** 2021-07-20 18:42 UTC
Labels: spb/tech, windows-hardware/prod
