### ISSUE TITLE
load dbgeng.dll error

### ISSUE THREAD

**Issue by heruix** [MicrosoftDocs/windows-driver-docs#676] opened 2018-07-21 03:54 UTC
SymSetDiaSession Can not find in dbgeng.dll ，so can‘t open windbg preview！

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c1e093f9-7df0-17ab-71ae-8af9003ee041
* Version Independent ID: 55ed6fd3-a7a6-f7d5-2a8e-fbf6cc6e2c7b
* Content: [Debugging Using WinDbg Preview](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/debugger/debugging-using-windbg-preview)
* Content Source: [windows-driver-docs-pr/debugger/debugging-using-windbg-preview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debugging-using-windbg-preview.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by heruix** [comment] 2018-07-21 04:04
<img width="220" alt="error windbg" src="https://user-images.githubusercontent.com/5779319/43031918-29c39618-8cde-11e8-94ee-6a492c4c8c8e.png">

**Comment by heruix** [comment] 2018-07-21 07:53
<img width="280" alt="load dbgeng" src="https://user-images.githubusercontent.com/5779319/43033515-1c17d360-8cfe-11e8-9b40-e6e712a33aa6.png">

**Comment by rzenko** [comment] 2018-07-25 09:58
any fix for this? i get the same errors

**Comment by rzenko** [comment] 2018-07-25 10:00
![error1](https://user-images.githubusercontent.com/37141225/43194274-577800ac-9045-11e8-8dc2-f1c048fafea1.png)
![error2](https://user-images.githubusercontent.com/37141225/43194282-59b1ee82-9045-11e8-9838-1223e8283722.png)

**Comment by DOMARS** [comment] 2018-07-27 23:50
I checked with the dev team and they are looking into this.

**Comment by rzenko** [comment] 2018-08-02 06:25
Ahh you are right. I feel like a noob!
Renamed C:\Windows\System32\dbghelp.dll to C:\Windows\System32\_dbghelp.dll and now everything is fine

**Comment by DOMARS** [comment] 2018-08-16 20:00
Closing as it looks like the issue has been identified and a work around exists.

**Closed by DOMARS** 2018-08-16 20:00 UTC
Labels: assigned-to-author, in-progress, product-feedback

**Comment by karstenBriksoft** [comment] 2018-11-16 11:38
this problem still exists today. the workaround to replace the file in system32 is impractical due to window's security restrictions. i.e. I can't move, rename or replace the file in system32. It's also surprisingly complicated to access the WinDBG installation in first place.

**Comment by ostefano** [comment] 2018-11-19 22:20
I agree. This is still broken, and the workaround is not a silver bullet.

**Comment by WeaponizedMeme** [comment] 2018-12-04 07:56
Why the hell is this still not fixed? Jesus fucking christ.

**Comment by lctrcl** [comment] 2018-12-04 08:55
Yeah, very frustrating, fresh Win10 installation and VMware Fusion, same error and the workaround doesn't work as well, after replacing `dbghelp.dll` in `system32` system stopped booting at all.

**Comment by kbandla** [comment] 2018-12-18 02:35
Just ran into this issue on a new windows VM, and I needed a workaround. The problem seems to happen because of VMWare's SVGA 3D drivers, which are part of the VMware Tools that get installed on VMs:
> C:\Windows\SYSTEM32\vm3dum64_loader.dll
> C:\Windows\system32\vm3dum64.dll

These DLLs seem to load the %SYSTEM% dbg dll, causing the issue. 

## Workaround 

So instead of touching the DLLs in the %SYSTEM% folder, 
* copy the contents of the Windbg Preview App, to a new directory
* copy the appropriate `dbghelp.dll` to the root of this new directory from the `amd64` or `x86` directory 

In a new command window:
```
cd Desktop
mkdir windbg_app
robocopy "C:\Program Files\WindowsApps\Microsoft.WinDbg_1.1811.26004.0_neutral__8wekyb3d8bbwe" windbg_app /s /e
cd windbg_app 
```
Then, if you are on an x64 system:
`copy amd64\dbghelp.dll .`
Or if you are on an x86 system:
`copy x86\dbghelp.dll`

That is it. You should now be able to run `DbgX.Shell.exe` from the new directory (windbg_app in the above example)

**Comment by DOMARS** [comment] 2018-12-18 19:14
@aluhrs13 - Possible alternative work around for VMWare dbghelp.dll issue. Not sure updates will work with the moved app directory on the desktop.

**Comment by shankar-ray** [comment] 2019-02-08 20:57
> Confirm the problem still exists.
> Most hassle-free workaround I found so far was disabling VMware's 3D graphics acceleration from the VM's Display hardware settings.

@ibookstein you are a Genius!

**Comment by ocitrev** [comment] 2019-02-19 14:00
I had the same problem and it was caused by NVIDIA GeForce Experience.  I uninstalled and WinDbg Preview works fine now.

**Comment by xslattery** [comment] 2019-02-23 08:30
I can confirm, uninstalling NVIDIA GeForce Experience, fixes it for me.

**Comment by craniumrat** [comment] 2019-02-23 13:51
Can confirm. I just uninstalled NVIDIA GeForce Experience. Windbg Review fired right back up.

**Comment by lovdov** [comment] 2019-02-27 11:49
It seems that recent nvidia update fucked windows up.
Nice job Nvidia as always

**Comment by lwahonen** [comment] 2019-03-02 08:40
WinDBG only works if vmware tools are uninstalled, which makes for a pretty sad user experience.

**Comment by Ch40zz** [comment] 2019-03-10 12:27
Simple fix application without any error checking.
Feel free to add error handling yourself:

```
STARTUPINFOA si = { sizeof(STARTUPINFOA) };
PROCESS_INFORMATION pi = { 0 };
CreateProcessA("C:\\Program Files\\WindowsApps\\Microsoft.WinDbg_1.1902.7001.0_neutral__8wekyb3d8bbwe\\DbgX.Shell.exe", 0, 0, 0, FALSE, CREATE_SUSPENDED, 0, 0, &si, &pi);

char szPath[] = "C:\\Program Files\\WindowsApps\\Microsoft.WinDbg_1.1902.7001.0_neutral__8wekyb3d8bbwe\\amd64\\dbghelp.dll";
void *dllPath = VirtualAllocEx(pi.hProcess, 0, sizeof(szPath), MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
WriteProcessMemory(pi.hProcess, dllPath, szPath, sizeof(szPath), 0);
HANDLE hThread = CreateRemoteThread(pi.hProcess, 0, 0, (LPTHREAD_START_ROUTINE)LoadLibraryA, dllPath, 0, 0);

WaitForSingleObject(hThread, INFINITE);

typedef NTSTATUS (__stdcall *tNtResumeProcess)(HANDLE ProcessHandle);
tNtResumeProcess NtResumeProcess = (tNtResumeProcess)GetProcAddress(GetModuleHandleA("ntdll.dll"), "NtResumeProcess");
NtResumeProcess(pi.hProcess);
```

What does this code do?
It starts Windbg Preview in suspended state, then injects dbghelp.dll before any other software such as GeForce Experience can inject their dll to load the wrong dbghelp from System32.
Lets hope this gets fixed some day without the need of using DLL injection lol

**Comment by WeaponizedMeme** [comment] 2019-03-18 23:26
It is now 2019 and this bug is STILL not fixed. People now need to debug Microsoft's debugger? Is that really what this has come to?

**Comment by goabout2** [comment] 2019-03-20 13:05
It is now 2019 and this bug is STILL not fixed. People now need to debug Microsoft's debugger? Is that really what this has come to?

**Comment by eraser2021999** [comment] 2019-03-24 19:16
2019 here and we still have this issue. :( My workaround was to disable Gamestream from Nvidia GeForce Experience.

**Comment by 0x43434343** [comment] 2019-04-13 21:34
Apr 13th , still has the same problem, any update for that?

**Comment by theevilbit** [comment] 2019-06-13 11:22
> Closing as it looks like the issue has been identified and a work around exists.
Workaround is not a fix, please reopen.

**Comment by aluhrs13** [comment] 2019-06-13 15:46
> > Closing as it looks like the issue has been identified and a work around exists.
> > Workaround is not a fix, please reopen.

This repo is for tracking documentation issues, not product issues. The correct GitHub issue tracking this is at - https://github.com/microsoftfeedback/WinDbg-Feedback/issues/2#issuecomment-495297591
