### ISSUE TITLE
Customer feedback - 

### ISSUE THREAD

**Issue by chigozyie** [MicrosoftDocs/windows-driver-docs#3760] opened 2023-12-30 01:49 UTC
### Type of issue

Other (describe below)

### Feedback

![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/135535292/d220f590-261a-484a-94ab-b347fdf79902)
How do I fix this problem

### Page URL

https://learn.microsoft.com/en-gb/windows-hardware/drivers/debugger/bug-check-0x124---whea-uncorrectable-error

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x124---whea-uncorrectable-error.md

### Author

@DOMARS

**Comment by tedhudek** [comment] 2024-01-02 16:49
Hi @chigozyie, while this documentation is for commercial driver developers, there are a couple potential causes for that error in the Cause section of the doc page.

For consumer driver issues, your best bet is to look at the Microsoft Help topics that are on support.microsoft.com.  You might start with https://support.microsoft.com/en-US/windows/resolving-blue-screen-errors-in-windows-60b01860-58f2-be66-7516-5c45a66ae3c6.

 Best of luck with your issue.

**Closed by tedhudek** 2024-01-02 16:49 UTC
Labels: Pri3
