### ISSUE TITLE
Web page typographic error

### ISSUE THREAD

**Issue by HeMinzhang** [MicrosoftDocs/windows-driver-docs#2561] opened 2020-10-27 13:28 UTC
![QQ截图20201027212752](https://user-images.githubusercontent.com/2683269/97307981-516c9480-189b-11eb-89ce-726bd7713811.png)

https://docs.microsoft.com/en-us/windows/win32/api/fwpstypes/ns-fwpstypes-fwps_filter1

**Comment by HeMinzhang** [comment] 2020-10-27 13:29
![QQ截图20201027212906](https://user-images.githubusercontent.com/2683269/97308131-79f48e80-189b-11eb-8197-f50c8feec6c5.png)

**Comment by anjoy8** [comment] 2020-10-27 13:34
Yes, I found that too.
Browser configuration: Chrome Browser, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64;  X64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

**Comment by foxdave** [comment] 2020-10-27 13:40
up

**Comment by EliotSeattle** [comment] 2020-10-27 16:05
@GrantMeStrength, this one's logged in drivers but the content is in win32. Formatting issue on a ref topic.

Feel free to open a new issue in the win32 repo and point to it from here, and I'll close this.

**Comment by hsebs** [comment] 2020-11-18 15:29
@HeMinzhang, It caused by unpaired tag `</div>`. 
I've fixed the issue, but it takes few days for it to be applied to the page.

**Comment by GrantMeStrength** [comment] 2020-11-18 17:51
Yup, we are experiencing a small delay with the publishing pipeline. Should go live soon. Thanks!

**Comment by hsebs** [comment] 2020-11-21 11:10
@EliotSeattle, It is fixed and applied on page. Could you close this issue?

**Closed** 2020-11-22 19:44 UTC
Labels: Pri3, doc-bug
